import LegalPage from "../components/LegalPage/LegalPage";

export const metadata = {
  title: "Data Protection Addendum | PJSoftTech",
  description: "Data Protection Addendum for PJSoftTech Pvt. Ltd.",
};

const sections = [
  {
    title: "1. Data Information",
    paragraphs: [
      "Our company does not store any data generated by us about you. We only keep information about your institute/school/firm/company which is suitable for us to provide you timely service, except the information you provide to us while registering Process KYC. We do not keep any other information except.",
    ],
  },

  {
    title: "2. OTP and Password Protection",
    paragraphs: [
      "Our company or our employees or technical team will never ask you for OTP or Username/Password. Do not give OTP or Username/Password to our company or company employee or technical team.",
    ],
  },

  {
    title: "3. Data Protection",
    paragraphs: [
      "If your software/services plan is valid then you will have to renew the plan within 90 days after the last day. Otherwise, after the 90 days (3 months) it will go to Grace Paired and after that, it will remain safe with us for 270 days (12 months). After the completion of 365 days, you will not be able to ask us for your data. Please note that. You should save your data within 365 days by downloading it in an organized manner. Otherwise, we will not commit to giving it to you after 365 days.",

      "If you do not like our service, you can stop it at any time. But if you want to access your data, you will have to pay a data maintenance fee. Data maintenance fee will be as per your plan:",
    ],

    items: [
      "Basic Plan: ₹2000 per year",
      "Premium Plan: ₹4000 per year",
      "Business Plan: ₹10000 per year",
    ],
  },

  {
    title: "Data Maintenance",
    paragraphs: [
      "This fee allows only viewing, sorting, filtering, and downloading data. You will not be able to add any new entries.",

      "In future, we will be updating our data maintenance cost/plans from time to time. For this, please always visit our page.",
    ],
  },

  {
    title: "4. Contact Us",
    paragraphs: [
      "If you have any questions or concerns about this Data Protection or our data practices, please contact us at:",

      "PJSoftTech Pvt. Ltd.",

      "203, 2nd Floor, Mangalmurti Complex, behind ABIL Tower, Hirabagh Chowk, Tilak Road, Shukrawar Peth, Pune-411002, India",

      "Email: sales@pjsofttech.com",

      "Phone: +91 9923570901",
    ],
  },
];

export default function DataProtectionAddendumPage() {
  return (
    <LegalPage
      title="Data Protection Addendum"
      sections={sections}
    />
  );
}